baseURL: http://chomic.net/
languageCode: en-gb
title: gabe chomic
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Divergent Crow
  description: "Profile and thoughts of Gabe Chomic"
  keywords: [Blog, Portfolio, PaperMod, Neurodivergence, Security, infosec]
  author: gabe
  # author: ["Me", "You"] # multiple authors
#  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShareButtons: ["linkedin", "reddit"]

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Divergent Crow
    subtitle: "Profile and thoughts of Gabe"
    imageUrl: "gabe_75th_cropped.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: CV
        url: vitae
      - name: About
        url: abouts

  socialIcons:
    - name: bluesky
      url: "https://bsky.app/profile/infoseccrow.bsky.social"
    - name: mastodon
      url: "https://chaos.social/@infoseccrow"
    - name: linkedin
      url: "https://www.linkedin.com/in/gchomic/"
    - name: twitter
      url: "https://twitter.com/infoseccrow"
    - name: github
      url: "https://github.com/gcrow"
    - name: spotify
      url: "https://open.spotify.com/user/tyranny12"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
